# version: '3.1'

services:
  me-rabbitmq:
    image: "rabbitmq:3.8.19-management" #version
    container_name: "me-rabbitmq"
    hostname: "me-rabbitmq"
    environment:
      SERVICE_NAME: "me-rabbitmq"
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG" #
      RABBITMQ_DEFAULT_USER: "rabbitmq" #creo un usuario
      RABBITMQ_DEFAULT_PASS: "rabbitmq" #creo el password
      RABBITMQ_DEFAULT_VHOST: "/"
    expose: #los puertos para exponerlos dentro d la red y otros contenedores puedan atacarlos
      - 5671
      - 5672
      - 15672
    ports: #mapea los puertos puerto del ordenador:ppuerto del contenedor
      - 5671:5671
      - 5672:5672
      - 15672:15672

  me-influxdb:
    image: "influxdb:2.0.7"
    container_name: "me-influxdb"
    hostname: "me-influxdb"
    environment:
      SERVICE_NAME: "me-influxdb"
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: manolo
      DOCKER_INFLUXDB_INIT_PASSWORD: MeusadlrHP_2021
      DOCKER_INFLUXDB_INIT_ORG: bjumper
      DOCKER_INFLUXDB_INIT_BUCKET: bjumper-bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 1ETU3JyH-if50k0mxP4okFQuoCWNjQl51QVzjT5hOADOVhyqHvB3xK1DWjgUULFZFEcXrx7utfCwx1Tb79rwEA==
    expose:
      - 8086
    ports:
      - 8086:8086

  me-telegraf-consumer:
    image: "telegraf:1.19.1"
    container_name: "me-telegraf-consumer"
    hostname: "me-telegraf-consumer"
    environment:
      SERVICE_NAME: "me-telegraf-consumer"
    volumes:
      - ./telegraf-consumer.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - me-influxdb
      - me-rabbitmq
